name: flutter_hive_cache_data_sync
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  # go_router: ^7.1.1
  freezed: ^2.4.1
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # go_router_builder: ^2.0.2
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
