name: flutter_hive_cache_data_sync

packages:
  - packages/**
  - apps/**
  - ./*

scripts:
  # Dependencies
  pub:get:
    run: |
      dart pub global run melos exec --fail-fast --  "dart pub get"
    description: Run `pub get` in all the packages

  build_runner:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run build_runner build --delete-conflicting-outputs
    description: Run all build runner to generate code.
    packageFilters:
      dependsOn: build_runner

  build_runner:watch:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub run build_runner watch --delete-conflicting-outputs
    description: Run all build runner to generate code.
    packageFilters:
      dependsOn: build_runner

  add:package:
    run: |
      dart pub global run melos exec --fail-fast -- \
        flutter pub add dart_code_metrics --dev
    description: |
      Add package all.

  postclean: >
    dart run melos exec -- "flutter clean"
